-- MySQL Script generated by MySQL Workbench
-- 04/25/17 19:22:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS proyectoFinal2017 DEFAULT CHARACTER SET utf8 ;
USE proyectoFinal2017 ;

-- -----------------------------------------------------
-- Table mydb.Usuarios
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS proyectoFinal2017.Usuarios (
  IdUsuario INT NOT NULL AUTO_INCREMENT,
  Email VARCHAR(45) NOT NULL,
  Password VARCHAR(45) NOT NULL,
  UltimoAcceso TIMESTAMP NULL,
  Bloqueado SET('s', 'n') NULL,
  Tipo SET('u', 'a') NULL,
  PRIMARY KEY (IdUsuario),
  UNIQUE INDEX Email_UNIQUE (Email ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.Clientes
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS proyectoFinal2017.Clientes (
  IdCliente INT NULL AUTO_INCREMENT,
  NIF VARCHAR(9) NOT NULL,
  Nombre VARCHAR(45) NOT NULL,
  Apellido1 VARCHAR(45) NOT NULL,
  Apellido2 VARCHAR(45) NULL,
  Email VARCHAR(45) NULL,
  Telefono VARCHAR(9) NULL,
  PRIMARY KEY (IdCliente),
  UNIQUE INDEX NIF_UNIQUE (NIF ASC),
  CONSTRAINT usuario
    FOREIGN KEY (IdCliente)
    REFERENCES mydb.Usuarios (IdUsuario)
    ON DELETE CASCADE
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.Viviendas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS proyectoFinal2017.Viviendas (
  IdVivienda INT NOT NULL AUTO_INCREMENT,
  Tipo VARCHAR(45) NOT NULL,
  IdCliente INT NULL,
  PRIMARY KEY (IdVivienda),
  INDEX usuVivienda_idx (IdCliente ASC),
  CONSTRAINT usuVivienda
    FOREIGN KEY (IdCliente)
    REFERENCES mydb.Clientes (IdCliente)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.CaractsViv
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS proyectoFinal2017.CaractsViv (
  IdCaractsViv INT NOT NULL AUTO_INCREMENT,
  IdVivienda INT NOT NULL,
  M2 INT NULL,
  Habitaciones INT NULL,
  PRIMARY KEY (IdCaractsViv),
  INDEX Vivienda_idx (IdVivienda ASC),
  CONSTRAINT Vivienda
    FOREIGN KEY (IdVivienda)
    REFERENCES mydb.Viviendas (IdVivienda)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.ImagenesViviendas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS proyectoFinal2017.ImagenesViviendas (
  IdImagenesViviendas INT NOT NULL AUTO_INCREMENT,
  IdVivienda INT NOT NULL,
  Imagen VARCHAR(45) NOT NULL,
  PRIMARY KEY (IdImagenesViviendas, IdVivienda),
  INDEX imgVivienda_idx (IdVivienda ASC),
  CONSTRAINT imgVivienda
    FOREIGN KEY (IdVivienda)
    REFERENCES mydb.Viviendas (IdVivienda)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table mydb.Preferencias
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS proyectoFinal2017.Preferencias (
  IdPreferencias INT NOT NULL,
  IdCliente INT NOT NULL,
  Preferencia VARCHAR(45) NOT NULL,
  PRIMARY KEY (IdPreferencias, IdCliente),
  INDEX prefClientes_idx (IdCliente ASC),
  CONSTRAINT prefClientes
    FOREIGN KEY (IdCliente)
    REFERENCES mydb.Clientes (IdCliente)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
